# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 04:22
from __future__ import unicode_literals

import apps.posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170613_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.posts.models.upload_location, width_field='width_field'),
        ),
    ]
